blog_platform/urls.py
from django.contrib import admin
from django.urls import include, path
from theme import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theme/', include('theme.urls')),
    path('', views.index),
    path('user/', include('user.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/urls.py
from django.contrib import admin
from django.urls import include, path

from theme.views import RedirectLike,, PostListView
from theme import views


app_name = 'theme'

urlpatterns = [
    path('', views.index, name='index'),
    path('creat_post', views.creat, name='creat'),
    path('<str:slug>/', views.detail, name='detail'),
    path('<str:slug>/edit', views.edit, name='edit'),
    path('<int:comment_id>/del-comment', views.delete_own_comment, name='del_comment'),
    path('<str:slug>/del-post', views.delete_own_post, name='del_post'),
    path('<str:slug>/like', RedirectLike.as_view(), name='like-toggle'),
    path('art', PostListView.as_view(), name='article-list'),

]

user/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views

app_name = 'user'

urlpatterns = [
    path('', views.index),
    path('sing_up', views.sing_up, name='sing_up'),
    path('log_in', views.log_in, name='log_in'),
    path('log_out', views.log_out, name='log_out'),
    path('profile', views.index, name='profile'),
    path('change_profile', views.update_profile, name='change_profile')
]

theme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    post_title = models.CharField(max_length=200)
    post_text = models.TextField()
    pub_date = models.DateTimeField('pub_date', default=timezone.now)
    slug = models.SlugField(unique=True)
    view_count = models.PositiveIntegerField('view_count', default=0, blank=True)
    like_count = models.ManyToManyField(User, related_name='like')

    def generate_slug(self):
        return slugify(self.post_title)

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse("theme:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("theme:like-toggle", kwargs={"slug": self.slug})

    def get_api_like_url(self):
        return reverse("theme:like-api-toggle", kwargs={"slug": self.slug})

    def get_edit_url(self):
        return reverse('theme:edit', kwargs={'slug': self.slug})


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField()
    pub_date = models.DateTimeField('pub_date', default=timezone.now)

    def __str__(self):
        return self.comment_text

theme/forms.py
from django import forms
from theme.models import Post, Comment


class PostModelCreat(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'post_text']
        widgets = {
            'post_title': forms.Textarea(attrs={'rows': 2,
                                                'cols': 103,
                                                'class': "form-control ",
                                                'id': "inputdefault",
                                                }),
            'post_text': forms.Textarea(attrs={'rows': 30,
                                               'cols': 103,
                                               'class': "form-control input-lg creat-text",
                                               'id': "inputlg",
                                               })
        }
        labels = {
            'post_title': "Post Title",
            'post_text': 'Post Text'
        }


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        widgets = {
            'comment_text': forms.Textarea(attrs={
                'rows': 2,
                'cols': 100,
                'class': "form-control input-sm"
            })
        }


# class UserProfile(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'password']

theme/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponseNotFound
from django.contrib.auth import login, authenticate
from django.views.generic import RedirectView
from django.views.generic.list import ListView
from theme.models import Post, Comment
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.utils import timezone
from theme.forms import (
    PostModelCreat,
    CommentModelForm,
)


class PostListView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'theme/indexList'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    def get_queryset(self):
        query = self.request.GET.get('search_text')
        if query:
            return Post.objects.filter(post_title__icontains=search_text)
        else:
            return Post.objects.order_by('-view_count')
             


class RedirectLike(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        post = get_object_or_404(Post, slug=slug)
        user = self.request.user
        url_ = post.get_absolute_url()
        if user.is_authenticated:
            if user in post.like_count.all():
                post.like_count.remove(user)
            else:
                post.like_count.add(user)
        return url_




def index(request):
    # if request.method == 'POST':
        # latest_post_list = Post.objects.filter(
            # post_title__icontains=request.POST['search_text'])
    # else:
        # latest_post_list = Post.objects.order_by('-view_count')

    latest_post_list =  Post.objects.order_by('-view_count')
    query = request.GET.get('q')
    if query:
        latest_post_list = Post.objects.filter(
            post_title__icontains=query)

    # search_text = request.GET.get('search_text')
    # if search_text:
    #     latest_post_list = Post.objects.filter(post_title__icontains=search_text)
    # else:
    #     latest_post_list = Post.objects.order_by('-view_count')
    paginator = Paginator(latest_post_list, 6)
    page = request.GET.get('page')

    if page is None:
        page = 1
    posts = paginator.page(page)



    context = {
        'posts': posts
    }
    return render(request, 'theme/index.html', context)


def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    form = CommentModelForm(request.POST or None)
    if request.method == 'POST' and form.is_valid() and request.user:
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
        return redirect(reverse('theme:detail', args=(slug,)))

    Post.objects.filter(slug=slug).update(view_count=F('view_count') + 1)
    post.view_count += 1

    comments = post.comment_set.order_by('-pub_date')
    context = {
        'post': post,
        'comment': comments,
        'form': form
    }
    return render(request, 'theme/detail.html', context)


@login_required(login_url='user:log_in')
def creat(request):
    form = PostModelCreat(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        try:
            post.slug = post.generate_slug()
            post.save()
        except:
            messages.error(request, 'post with this title is already exist')
            return redirect(reverse('theme:creat'))
        

        return redirect(reverse('theme:index'))
    context = {
        'form': form
    }
    return render(request, 'theme/creat_post.html', context)


@login_required(login_url='user:log_in')
def edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostModelCreat(request.POST or None, instance=post)
    if request.user == post.author:
        if request.POST and form.is_valid():
            form.save()
            return redirect(reverse('theme:detail', args=(slug,)))
        context = {
            'form': form,
            'post': post
        }
        return render(request, 'theme/edit.html', context)
    return HttpResponseNotFound()


@login_required(login_url='user:log_in')
def delete_own_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.author == request.user:
        comment.delete()
    return redirect(reverse('theme:detail', args=(comment.post.slug,)))


@login_required(login_url='user:log_in')
def delete_own_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.author == request.user:
        messages.success(request, 'post delete successful')
        post.delete()
    return redirect(reverse('theme:index'))

theme/templates/theme/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'theme/index_style.css' %}">
</head>
<body>

<header>
    <div class="panel   panel-default">
        <div class="panel-body">

            <ul>
                <li>
                    <a class="bottom-logo" href="{% url 'theme:index' %}">
                        {% load staticfiles %}
                        <img src="{% static 'theme/img/dark_logo.png' %}" alt="LOGO" class="img-rounded">
                    </a>
                </li>
                <li>
                    <div>
                        <form action="{% url 'theme:index' %}" method="get">
                            {% csrf_token %}
                            <input type="text" name="q" value="{{ request.GET.q }}" required>
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span> Search
                            </button>
                        </form>
                    </div>
                </li>

                <li>
                    <div class="btn-primary"><a class="btn-primary" href="{% url 'theme:creat' %}">Creat new
                        Post</a>
                    </div>
                </li>
                <li>
                    {% if  user.is_authenticated %}
                        <p>{{ user.username }}</p>
                        {% if user.profile.avatar %}
                            <img src="{{user.profile.avatar.url}}" width="50" height="50">
                        {% endif %} 
                        <a href="{% url 'user:log_out' %}">log out</a>

                        <a href="{% url 'user:profile' %}">my profile</a>

                    {% else %}
                        <a href="{% url 'user:sing_up' %}">sing up</a>

                        <a href="{% url 'user:log_in' %}">log in</a>
                    {% endif %}
                </li>
                <li></li>
            </ul>


        </div>
    </div>
</header>

<div class="container">
    <div class="jumbotron">

        {% if messages %}

            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}

        {% block content %}
        {% endblock %}

    </div>
</div>
</body>
</html>

theme/templates/theme/creat_post.html
{% extends 'theme/base.html' %}

{% block content %}

        <form method="post" action="{% url 'theme:creat' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>

{% endblock %}

theme/templates/theme/detail.html
{% extends 'theme/base.html' %}

{% block content %}

    {% if post %}

        {{ post.like_count.count }} <a href="{% url 'theme:like-toggle' post.slug%}">like</a>
        <h1>{{ post.post_title }}</h1>
        {{ post.view_count }}
        <br>
        {{ post.pub_date }}
        <br>
        {{ post.author }}

        <div class="well">{{ post.post_text|linebreaksbr }}</div>

        {% if user ==  post.author %}
            <a href="{% url 'theme:edit' post.slug %}">Edit post</a>
            <a href="{% url 'theme:del_post' post.slug%}">Del post</a>
        {% endif %}

    {% else %}
        <p>This post is not available.</p>
    {% endif %}

    {% if user.is_authenticated %}
        <form action="{% url 'theme:detail' post.slug %}" method="post">
            {% csrf_token %}
            {{ form }}
            <div class="form-group">
                <input type="submit" class="btn-danger">
            </div>
        </form>
    {% endif %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <ul class="list-group">
        {% for c in comment %}
            <li>
                <div class="well ">{{ c.comment_text|linebreaks }} {{ c.author }} {{ c.pub_date }}
                    {% if c.author == user %}
                        <a href="{% url 'theme:del_comment' c.id%}">del</a>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

theme/templates/theme/edit.html
{% extends 'theme/base.html' %}

{% block content %}

            <form action="{% url 'theme:edit' post.slug %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit">
            </form>

{% endblock %}

theme/templates/theme/index.html
{% extends 'theme/base.html' %}
{% block content %}

{% if posts %}
    {% for post in posts %}
        <div class="well">
            <a href="{% url 'theme:detail' post.slug %}">
                {{ post.post_title }}
                {{ post.author }}</a>
        </div>
    {% endfor %}

    <ul class="pagination">

        {% if posts.has_previous %}
            <li class="waves-effect"><a href="?page=
                    {{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                    class="material-icons">&ltrif; </i></a></li>
            {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons">&ltrif;</i></a></li>
                {%endif%}

        {% for i in posts.paginator.page_range %}
            <li><a href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}

        {% if posts.has_next %}
            <li class="waves-effect"><a
                    href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i
                    class="material-icons">&rtrif;</i></a></li>
        {% else %}

            <li class="disabled"><a href="#!"><i class="material-icons">&rtrif;</i></a></li>
        {% endif %}
    </ul>

{% else %}
    <h1>No post are available</h1>
{% endif %}

{% endblock %}