blog_platform/urls.py
from django.contrib import admin
from django.urls import include, path
from theme import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theme/', include('theme.urls')),
    path('', views.index),
    path('user/', include('user.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/urls.py
from django.contrib import admin
from django.urls import include, path

from theme.views import RedirectLike,, PostListView
from theme import views


app_name = 'theme'

urlpatterns = [
    path('', views.index, name='index'),
    path('creat_post', views.creat, name='creat'),
    path('<str:slug>/', views.detail, name='detail'),
    path('<str:slug>/edit', views.edit, name='edit'),
    path('<int:comment_id>/del-comment', views.delete_own_comment, name='del_comment'),
    path('<str:slug>/del-post', views.delete_own_post, name='del_post'),
    path('<str:slug>/like', RedirectLike.as_view(), name='like-toggle'),
    path('art', PostListView.as_view(), name='article-list'),

]

user/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views

app_name = 'user'

urlpatterns = [
    path('', views.index),
    path('sing_up', views.sing_up, name='sing_up'),
    path('log_in', views.log_in, name='log_in'),
    path('log_out', views.log_out, name='log_out'),
    path('profile', views.index, name='profile'),
    path('change_profile', views.update_profile, name='change_profile')
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    bio = models.TextField(max_length=500, blank=True, default="")
    avatar = models.FileField(upload_to='avatar/', blank=True, null=True, default='/default/default_avatar.png')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from user.models import Profile


class UserLogIn(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class UserCreat(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'avatar')

user/views.py
from django.core.checks import messages
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from theme.models import Post, Comment
from user.forms import (
    UserLogIn,
    UserCreat,
    UserForm,
    ProfileForm
)


@login_required(login_url='user:log_in')
def index(request):
    user = request.user
    users_post = Post.objects.filter(author=user)
    users_comment = Comment.objects.filter(author=user)
    context = {
        'users_post': users_post,
        'users_comment': users_comment
    }
    return render(request, 'user/index.html', context)


def sing_up(request):
    user_form = UserCreat(request.POST or None)
    if request.method == 'POST' and user_form.is_valid():
        user_form.save()
        username = user_form.cleaned_data.get('username')
        raw_password = user_form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(request, user)

        return redirect(reverse('theme:index'))
    context = {
        'form': user_form
    }
    return render(request, 'user/sing_up.html', context)


def log_in(request):
    form = UserLogIn()
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('theme:index'))
        else:
            messages.error(request, 'invalid login or password')
            return render(request, 'user/log_in.html', {'form': form})
            
    content = {
        'form': form
    }
    return render(request, 'user/log_in.html', content)


def log_out(request):
    logout(request)
    return redirect(reverse('theme:index'))


@login_required(login_url='user:log_in')
def update_profile(request):
    user = request.user
    if request.method == 'POST':

        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)

        if user_form.is_valid() and profile_form.is_valid():

            user_form.save()
            profile_form.save()

            return redirect('user:profile')
        else:
            return redirect('theme:index')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'user/change_profile.html', context)

user/templates/user/change_profile.html
{% extends 'theme/base.html' %}

{% block content %}

    <form action="{% url 'user:change_profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

user/templates/user/index.html
{% extends 'theme/base.html' %}

{% block content %}
    user name: {{ user.username }}
    <br>
    first name: {{ user.first_name }}
    <br>
    last name: {{ user.last_name }}
    <br>
    bio: {{ user.profile.bio }}

    
    <br>
    <a href="{% url 'user:change_profile' %}">change my profile</a>
    <h4>my post</h4>

    {% for post in users_post %}
        <div class="well">
            <a href="{% url 'theme:detail' post.slug %}">
                {{ post.post_title }}
            </a>

        </div>
    {% endfor %}



{% endblock %}

user/templates/user/log_in.html
{% extends 'theme/base.html' %}

{% block content %}


    <form action="{% url 'user:log_in' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
        {% if error_massage %}
            <div class="error_massage">{{ error_massage }}</div>
        {% endif %}
    </form>
{% endblock %}

user/templates/user/sing_up.html
{% extends 'theme/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          {{ autoescape }}
        {% endif %}
        {% for error in field.errors %}
          <div class="error_massage">{{ error }}</div>
        {% endfor %}

    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}